# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: "Mimic3 TTS Server"
version: "0.2.0"
slug: mimic3tts
stage: experimental
description: "Mimic3, a fast and offline neural tts system"
url: "https://github.com/Oliver2213/ha-addons/tree/main/mimic3-tts-server"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
init: false
ports:
  59125/tcp: 59125
ports_description:
  59125/tcp: Port for mimic3-server
